version: '3.8'

services:
  dj-mariadb:
    image: mariadb
    container_name: dj-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    command: --max-connections=1000
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  domserver:
    image: domjudge/domserver:latest
    container_name: domserver
    depends_on:
      - dj-mariadb
    environment:
      MYSQL_HOST: dj-mariadb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DOMJUDGE_PORT}:80"
    volumes:
      - domjudge_config:/opt/domjudge/etc
      - domserver_config:/opt/domjudge/domserver/etc
      - domjudge_logs:/opt/domjudge/domserver/log
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - dj-mariadb
    environment:
      PMA_HOST: dj-mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    restart: unless-stopped

volumes:
  mariadb_data:
  domjudge_config:
  domserver_config:
  domjudge_logs:
